### ISSUE TITLE
[FEA] Dedicated objects for columns_ctx, stats_ctx, phase, config

### ISSUE THREAD

**Issue by benfred** [NVIDIA/NVTabular#15]
<a href="https://github.com/alecgunny"><img src="https://avatars0.githubusercontent.com/u/14932242?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [alecgunny](https://github.com/alecgunny)**
_Tuesday Mar 24, 2020 at 19:28 GMT_
_Originally opened as https://github.com/rapidsai/recsys/issues/28_

----

**Is your feature request related to a problem? Please describe.**
Right now many of the central objects in a Workflow are constructed as lists or dicts with some expected structure. This can make parsing their meaning and use, as well as those of the constituent elements, difficult to understand when trying to debug or contribute. Examples include the columns_ctx, stats_ctx, phases, and the workflow config.

**Describe the solution you'd like**
Ideally, these objects would be replaced with dedicated objects with descriptive attributes and methods that make their functionality and components more clear. Methods on these objects could even simplify Workflow code by replacing methods which exist solely to update and retrieve information from these objects.

**Describe alternatives you've considered**
NamedTuples, or objects inheriting from NamedTuples, could be a simple way to ascribe fixed attributes, and could even maintain iterability to reduce short-term code updates.

**Comment by benfred** [comment]
<a href="https://github.com/alecgunny"><img src="https://avatars0.githubusercontent.com/u/14932242?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [alecgunny](https://github.com/alecgunny)**
_Thursday Apr 23, 2020 at 19:04 GMT_

----

Expanding scope to include feedback on relationships between objects. Pseudo code demo can be found here https://github.com/alecgunny/pseudo_nvt (Even and Julio should have access already, let me know if anyone else wants to be added)

**Comment by benfred** [comment]
<a href="https://github.com/alecgunny"><img src="https://avatars0.githubusercontent.com/u/14932242?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [alecgunny](https://github.com/alecgunny)**
_Friday May 01, 2020 at 15:22 GMT_

----

At its core, this is the gist of the sort of flow I think might make sense: putting less omnibus functionality into the workflow and breaking things up into separate function calls:
```
workflow = nvt.Workflow(...)

train_dataset = nvt.dataset('train.csv', batch_size=8192)
valid_dataset = nvt.dataset('valid.csv', batch_size=8192)

stats_context = nvt.stats.StatsContext(workflow)
stats_context.fit(train_dataset)

train_dataset.map(workflow, stats_context=stats_context)
valid_dataset.map(workflow, stats_context=stats_context)

output_path = '/output/path'
nvt.write_parquet_dataset(
    train_dataset,
    os.path.join(output_path, 'train/*.parquet'),
    shuffle=True)
nvt.write_parquet_dataset(
    valid_dataset,
    os.path.join(output_path, 'valid/*.parquet'),
    shuffle=False)
stats_context.dump(os.path.join(output_path, 'stats_context.pickle'))
```

**Comment by alecgunny** [comment]
I'd like to re-up this in light of recent issues I've had trying to glean information from the `columns_ctx` for applications like workflow chaining (and validating that the output of one workflow is valid to plug into the next).

Issues include:
- If any sort of op is applied to a  Workflow, that group of feature's output in the `Workflow.columns_ctx["final"]["ctx"]` just has the op name applied, but doesn't tell you the names of the columns that will come out of that op. Is this the expected/desired behavior? If someone wanted that information, would they then have to write a loop to go through each op and figure out what the name of the resulting output columns would be?
- If "ctx" is the only key in the `Workflow.columns_ctx["final"]` dictionary, why is it there at all? It doesn't seem to be consistent with how values are formatted in other fields of the columns context. A dedicated object spec would help to make this more clear (e.g. users would know that if they want the final categorical columns to look in `Workflow.columns_ctx["final"]["ctx"]["categorical"]` rather than `Workflow.columns_ctx["final"]["categorical"]`, which they might expect on intuition alone)

**Comment by benfred** [comment]
We've eliminated the columns_ctx, stats_ctx, phase,config objects entirely with the 0.4 api changes .
