### ISSUE TITLE
[BUG] Categorical encoding of unknown values 

### ISSUE THREAD

**Issue by benfred** [NVIDIA/NVTabular#312]
**Describe the bug**
When doing categorical encoding , unknown values in the validation set should be mapped to an unknown category (id 0) . However, when run without frequency caps - we're using 'search_sorted' to lookup the categorical ids. When the categorical isn't in the train set, this maps to the nearest key by sort order instead of setting to an unknown value.

**Steps/Code to reproduce bug**
```
import cudf
train = cudf.DataFrame({'user_id': [1, 2, 3, 5, 6], 'item_id': ["a", "g", "c", 'd', 'e']})
val = cudf.DataFrame({'user_id': [1, 2, 4, 7, 8], 'item_id': ["a", "b", "c", "a", "b"]})
proc = nvt.Workflow(
    cat_names=cat_names,
    cont_names= [],
    label_name=[])
proc.add_cat_preprocess(nvt.ops.Categorify())
```

Running this code shows the valid set ids get mapped to ``` 1, 2, 4, 0, 0``` when it should be ``` 1, 2, 0, 0, 0```.

**Comment by rjzamora** [comment]
I added the "good first issue" label, because I imagine an appropriate fix is to make the searchsorted algorithm an option.  Right now, we use this algorithm whenever [there is no frequency cap](https://github.com/NVIDIA/NVTabular/blob/b77fd7776631bb542ef99125a3c559f73f4143ed/nvtabular/ops/categorify.py#L737).  Instead, we could let the user specify the transformation algorithm they want - e.g. `algo="merge"` (default) or `algo="searchsorted"` (faster).

**Comment by AnshuTrivedi** [comment]
Hi @rjzamora @benfred I want to fix issue and contribute.Please assign  this issue to me.

**Comment by benfred** [comment]
Thanks @AnshuTrivedi  - we'd appreciate the contribution! Let me know how you make out =)

**Comment by rnyak** [comment]
@benfred @AnshuTrivedi Please also consider these cases:
```
train = cudf.DataFrame({'user_id': [1, 2, 3, 5, 6], 'item_id': ["a", "g", "c", 'd', 'e']})
val = cudf.DataFrame({'user_id': [1, 2, 4, 7, 8, np.nan, np.NAN], 'item_id': ["a", "b", "c", "a", "b", np.NAN, '']})
```

Notice that we have an empty entry in the `val` set. That entry should be counted as `unknown` and mapped to `0`.  However, the current `Categorify` is not considering it as a `Null` entry, and assigning `1` instead of `0`. That's the output after the categorify op:

```
gdf_val
	user_id	item_id
0	1	2
1	1	3
2	1	4
3	1	2
4	1	3
5	0	0
6	0	1
```
