### ISSUE TITLE
[FEA] Multi-Node testing / example

### ISSUE THREAD

**Issue by benfred** [NVIDIA/NVTabular#342]
We should test out how NVTabular performs on with multinode multigpu setups.  

We should get multiple machines on a cluster like Selene and use for testing.

We should also add notes on how to set up a multi-node dask cluster for use with NVT, or add links to other guides.

**Comment by albert17** [comment]
@rjzamora for visibility and questions.

Rick shared [this document](https://blog.dask.org/2020/07/23/current-state-of-distributed-dask-clusters) in the past in the slack channel and it is very good, we probably should include it. Maybe there are some other sources we could also include.

I see 2 initial options about how to use dask multinode: 
1. (This is the one I am exploring): Launch dask-cuda-worker in N machines and dask-scheduler in 1 machine; connect to the scheduler using `client = Client("tcp://address:port")`, and run the code. 

2. (I cannot test this in Selene): Use SSHCluster `(cluster = SSHCluster(["scheduler", "worker", "worker", "worker"])`), This is a bit more simple, since you don't have to manually start the scheduler and workers in the machines (You still have to had install the required software on them).


I have the following concerns:
* What does it happen with `device_limit`, `device_pool_size`, and `part_size ` here? They are calculated using `device_size` which it will be local to the machine. As far as I understand, this would work if all the machines have the same hardware? (i.e NxA100-40GB)
* Are we looking to support heterogenous cluster and automatic configuration? Or towards homogeneous cluster with user configuration (this one sounds more realistic to me)?
