### ISSUE TITLE
[FEA] JoinExternal option on nvt.Dataset  in addition to cudf

### ISSUE THREAD

**Issue by kkranen** [NVIDIA/NVTabular#370]
**Is your feature request related to a problem? Please describe.**
Currently, JoinExternal only supports cudf external tables. This works when the cudf table can be materialized, but in cases where the table you wish to join is large (for example, where the desired table to join is the dataset result of a workflow spread across many parquet files), the cudf table cannot be materialized directly and thus cannot be joined.

**Describe the solution you'd like**
Allow JoinExternal to accept nvt.Dataset as input.

**Describe alternatives you've considered**
Allow passing of multiple cudf dataframes into JoinExternal to be treated as a single dataframe 

**Additional context**
N/A

**Comment by EvenOldridge** [comment]
Rick, can you take a look at this?  From what I remember we implemented join before we were using dask_cudf, and I think there's some missing plumbing to make this work more easily.  Ideally we should be able to plug data from multiple sources in using the native join from dask_cudf.

**Comment by rjzamora** [comment]
Since `JoinExternal` is an `Operator`, it is required that the `transform` logic operates at the cudf/pandas level (not at the Dask-collection level).  Therefore, to join to an external `Dataset`/collection we will need to (within `transform`): (1) promote the target partition to a single-partition DataFrame-collection, (2) merge the promoted collection with the external Dataset/collection, and then (3) return a synchronously-computed result.  This might work, but would effectively mean that we are constrained to a broadcast-based join.

For more-complex join operations, we could always introduce a `Dataset.join_external` method.  However, I think it goes against the design of NVTabular to require inter-prtition shuffling within a transform operator.
