### ISSUE TITLE
[FEA] Only require name for LambdaOp if not replacing

### ISSUE THREAD

**Issue by alecgunny** [NVIDIA/NVTabular#382]
It seems like requiring a name for the `LambdaOp` as the very first arg, even before the function itself, might be a bit unintuitive and unnecessary for the case where `replace=True`. Would it make sense to make this a kwarg that defaults to None, and is only checked for when `replace=False`? In the `replace=True` case, you could create a random id or even just use `lambda` to be able to identify the created columns.

As potentially more complicated but useful behavior, `replace` could be a fed a string that is interpreted as the name to use (and the check for which makes sure to feed `replace=False` to `super().__init__`). For the `replace=True` case, if we want to use `lambda` but a `Workflow` has multiple `lambda` ops, the `Workflow` could do some checks at build time to assign the name of `lambda_{i}` for each `i` index of the `LambdaOp`s in the `Workflow`.

**Comment by benfred** [comment]
This is fixed with the new api changes - not only don't you have to define a name for the lambda op, but you can now also just directly use lambda's with having to wrap in a lambda op

Like for the outbrains example this handles the geo_location processing to split out the country and state from a string and then:
```
geo_location = ColumnGroup(["geo_location"])
state = geo_location >> (lambda col: col.str.slice(0, 5)) >> Rename(postfix="_state")
country = geo_location >> (lambda col: col.str.slice(0, 2)) >> Rename(postfix="_country")
geo_features = state + country + geo_location >> Categorify()

workflow = nvtabular.Workflow(geo_features + other_features)
```

(see https://nvidia.github.io/NVTabular/main/examples/outbrain.html#Feature-Engineering for how it looks on a bigger example).
