### ISSUE TITLE
[BUG] Getting error from HugeCTR inference notebook

### ISSUE THREAD

**Issue by rnyak** [NVIDIA/NVTabular#718]
I am getting this error from HugeCTR inference notebook when I send a request to TIS:

```
#placeholder variables for the output
outputs = []
outputs.append(httpclient.InferRequestedOutput("OUTPUT0"))
# make the request
with httpclient.InferenceServerClient("localhost:8001") as client:
    response = client.infer('movielens_ens', inputs, request_id=str(1), outputs=outputs)
print("predicted sigmoid result:\n", response.as_numpy("OUTPUT0"))
​```

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-27-62d693160d85> in <module>
      6     response = client.infer('movielens_ens', inputs, request_id=str(1), outputs=outputs)
      7 
----> 8 print("predicted sigmoid result:\n", response.as_numpy("OUTPUT0"))

/opt/conda/envs/merlin/lib/python3.8/site-packages/tritonclient/grpc/__init__.py in as_numpy(self, name)
   1630                 else:
   1631                     np_array = np.empty(0)
-> 1632                 np_array = np_array.reshape(shape)
   1633                 return np_array
   1634             else:

ValueError: cannot reshape array of size 64 into shape (3,)

```

**Comment by rnyak** [comment]
@oyilmaz-nvidia can you check this at your end? Thanks.

@benfred fyi.

**Comment by oyilmaz-nvidia** [comment]
@rnyak  I have tested this error with the merlin-inference:0.4 and merlin-inference:0.5 container and I only get it with the container 0.5. Everything looks fine with version 0.4. Will try to understand what's going on but right now I have no idea.

**Comment by benfred** [comment]
Joey said this is probably related to the JSON config we're generating for hugectr -

**Comment by oyilmaz-nvidia** [comment]
After investigating batch size issue, the root cause is that the hugectr is allocating the output buffer based on the max number of batch size even though they only send the generated output. Triton is complaining because of this allocated space.

HugeCTR team fixed this bug and hugectr backend can be installed in the merlin-inference container using the following commands;

Assuming HugeCTR is built already;

git clone  https://gitlab-master.nvidia.com/dl/hugectr/hugectr_inference_backend.git  hugectr_inference_backend 
cd hugectr_inference_backend
mkdir build && cd build 
cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr/local/hugectr .. 
make  
make install 

After applying these steps, I no longer get this error.
